Add shellcheck/shfmt

diff --git a/bin/git-deb-commit b/bin/git-deb-commit
--- a/bin/git-deb-commit
+++ b/bin/git-deb-commit
@@ -11,21 +11,21 @@ set -e
 
 DIR="$(pwd)"
 while [ ! -e "$DIR/changelog" ]; do
-  DIRNEW="$(dirname "$DIR")"
-  if [ "$DIR" = "$DIRNEW" ]; then
-    echo "Cannot find changelog" >&2
-    exit 1
-  fi
-  DIR="$DIRNEW"
+    DIRNEW="$(dirname "$DIR")"
+    if [ "$DIR" = "$DIRNEW" ]; then
+        echo "Cannot find changelog" >&2
+        exit 1
+    fi
+    DIR="$DIRNEW"
 done
 
 if [ -d "$DIR/.git" ]; then
-  GITDIR="$DIR"
+    GITDIR="$DIR"
 elif [ -d "$(dirname "$DIR")/.git" ]; then
-  GITDIR="$(dirname "$DIR")"
+    GITDIR="$(dirname "$DIR")"
 else
-  echo "Cannot find .git dir"
-  exit 1
+    echo "Cannot find .git dir"
+    exit 1
 fi
 
 commitmsg="$(perl -ne 'print; last if /^ -- /' "$DIR/changelog")"
