more upgrade-all-the-things

diff --git a/bin/upgrade-all-the-things b/bin/upgrade-all-the-things
--- a/bin/upgrade-all-the-things
+++ b/bin/upgrade-all-the-things
@@ -2,8 +2,12 @@
 
 set -e
 
+if [ -n "${DEBUG}" ]; then
+    set -x
+fi
+
 [ -n "${CHROOT_BASE}" ] || CHROOT_BASE="/srv/chroot"
-[ -n "${CHROOT_BLACKLIST}" ] || CHROOT_BLACKLIST=""
+[ -n "${CHROOT_BLACKLIST}" ] || CHROOT_BLACKLIST="gentoo"
 
 cd /
 
@@ -18,18 +22,31 @@ for c in $(cd "${CHROOT_BASE}" && ls -1); do
     done
     [ "$blacklisted" = "0" ] || continue
 
-    if [ -e "${CHROOT_BASE}/$c/etc/debian_version" ]; then
-        if ! chronic schroot -c $c -- /bin/sh -c "apt-get update && apt-get -u -y dist-upgrade && apt-get clean" 2>&1; then
+    if [ -n "${DEBUG}" ]; then
+        echo "Starting $c"
+        CHRONIC=""
+    else
+        CHRONIC="chronic"
+    fi
+    if [ -e "${CHROOT_BASE}/$c/etc/lsb-release" ] && \
+        grep -q "DISTRIB_ID=Ubuntu" "${CHROOT_BASE}/$c/etc/lsb-release" && \
+        grep -q "development branch" "${CHROOT_BASE}/$c/etc/lsb-release"; then
+        if ! $CHRONIC schroot -c $c -- /bin/sh -c "apt-get --allow-releaseinfo-change update && apt-get -u -y dist-upgrade && apt-get clean" 2>&1; then
+            failed="$failed $c"
+            echo "=== $c FAILED ==="
+        fi
+    elif [ -e "${CHROOT_BASE}/$c/etc/debian_version" ]; then
+        if ! $CHRONIC schroot -c $c -- /bin/sh -c "apt-get update && apt-get -u -y dist-upgrade && apt-get clean" 2>&1; then
             failed="$failed $c"
             echo "=== $c FAILED ==="
         fi
     elif [ -e "${CHROOT_BASE}/$c/usr/bin/dnf" ]; then
-        if ! chronic schroot -c $c -- /bin/sh -c "dnf -y update && dnf clean packages" 2>&1; then
+        if ! $CHRONIC schroot -c $c -- /bin/sh -c "dnf -y update && dnf clean packages" 2>&1; then
             failed="$failed $c"
             echo "=== $c FAILED ==="
         fi
     elif [ -e "${CHROOT_BASE}/$c/usr/bin/yum" ]; then
-        if ! chronic schroot -c $c -- /bin/sh -c "yum -y update" 2>&1; then
+        if ! $CHRONIC schroot -c $c -- /bin/sh -c "yum -y update" 2>&1; then
             failed="$failed $c"
             echo "=== $c FAILED ==="
         fi
