upgrade-all-the-things

diff --git a/bin/upgrade-all-the-things b/bin/upgrade-all-the-things
--- a/bin/upgrade-all-the-things
+++ b/bin/upgrade-all-the-things
@@ -2,12 +2,10 @@
 
 set -e
 
-[ -n "${LOG_DIR}" ] || LOG_DIR="/var/log/allthethings"
 [ -n "${CHROOT_BASE}" ] || CHROOT_BASE="/srv/chroot"
 [ -n "${CHROOT_BLACKLIST}" ] || CHROOT_BLACKLIST=""
 
 cd /
-mkdir -p "${LOG_DIR}"
 
 failed=""
 for c in $(cd "${CHROOT_BASE}" && ls -1); do
@@ -20,23 +18,22 @@ for c in $(cd "${CHROOT_BASE}" && ls -1); do
     done
     [ "$blacklisted" = "0" ] || continue
 
-    now="$(date +%s)"
-    echo "=== $c ($now) ==="
-    echo
     if [ -e "${CHROOT_BASE}/$c/etc/debian_version" ]; then
-        if ! schroot -c $c -- /bin/sh -c "apt-get update && apt-get -u -y dist-upgrade && apt-get clean" >"${LOG_DIR}/${now}.${c}.log" 2>&1; then
+        if ! chronic schroot -c $c -- /bin/sh -c "apt-get update && apt-get -u -y dist-upgrade && apt-get clean" 2>&1; then
             failed="$failed $c"
+            echo "=== $c FAILED ==="
         fi
     elif [ -e "${CHROOT_BASE}/$c/usr/bin/dnf" ]; then
-        if ! schroot -c $c -- /bin/sh -c "dnf -y update && dnf clean packages" >"${LOG_DIR}/${now}.${c}.log" 2>&1; then
+        if ! chronic schroot -c $c -- /bin/sh -c "dnf -y update && dnf clean packages" 2>&1; then
             failed="$failed $c"
+            echo "=== $c FAILED ==="
         fi
     elif [ -e "${CHROOT_BASE}/$c/usr/bin/yum" ]; then
-        if ! schroot -c $c -- /bin/sh -c "yum -y update" >"${LOG_DIR}/${now}.${c}.log" 2>&1; then
+        if ! chronic schroot -c $c -- /bin/sh -c "yum -y update" 2>&1; then
             failed="$failed $c"
+            echo "=== $c FAILED ==="
         fi
     fi
-    echo
 done
 
 if [ -n "$failed" ]; then
